[preferred]
default=gtk
org.freedesktop.impl.portal.FileChooser=slm
org.freedesktop.impl.portal.OpenURI=slm
org.freedesktop.impl.portal.Settings=slm
org.freedesktop.impl.portal.Notification=slm
org.freedesktop.impl.portal.Inhibit=slm
org.freedesktop.impl.portal.Screenshot=slm

