#include "SlmFstabJob.h"

#include <GlobalStorage.h>
#include <JobQueue.h>
#include <utils/Logger.h>

#include <QByteArray>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QString>
#include <QStringList>
#include <QVariantList>
#include <QVariantMap>

CALAMARES_PLUGIN_FACTORY_DEFINITION(SlmFstabJobFactory, registerPlugin<SlmFstabJob>();)

namespace {

constexpr const char *kHeader =
    "# SLM Desktop — generated by slm-installer, DO NOT EDIT MANUALLY\n";

constexpr const char *kEspOptions = "umask=0077,shortname=mixed";

// §2.4 requires the root row to carry space_cache=v2 even though the §2.3
// install-time mount sequence omits it (it's the default on Btrfs ≥ 5.15;
// being explicit in fstab prevents surprises on cross-distro chroots).
constexpr const char *kRootSubvol = "@";
constexpr const char *kRootSpaceCache = "space_cache=v2";

QString resolveRootMountPoint(Calamares::GlobalStorage *gs)
{
    const QString fromGs = gs->value(QStringLiteral("rootMountPoint")).toString();
    return fromGs.isEmpty() ? QStringLiteral("/mnt/slm-install-root") : fromGs;
}

// Subprocess `blkid -s UUID -o value <device>` and return the trimmed UUID,
// or an empty string on any failure. Callers decide whether empty is fatal.
QString readUuid(const QString &device)
{
    QProcess proc;
    proc.start(QStringLiteral("blkid"), { QStringLiteral("-s"), QStringLiteral("UUID"),
                                          QStringLiteral("-o"), QStringLiteral("value"),
                                          device });
    if (!proc.waitForStarted(2000) || !proc.waitForFinished(5000)) {
        return {};
    }
    if (proc.exitCode() != 0) {
        return {};
    }
    return QString::fromUtf8(proc.readAllStandardOutput()).trimmed();
}

QString formatRow(const QString &uuid, const QString &target, const QString &fsType,
                  const QString &options, int dumpFlag, int fsckOrder)
{
    return QStringLiteral("UUID=%1  %2  %3  %4  %5 %6\n")
        .arg(uuid, target, fsType, options)
        .arg(dumpFlag)
        .arg(fsckOrder);
}

QByteArray buildFstab(const QString &btrfsUuid, const QString &espUuid,
                      const QVariantList &mountPlan)
{
    QByteArray content;
    content.append(kHeader);
    for (const QVariant &entry : mountPlan) {
        const QVariantMap row = entry.toMap();
        const QString subvol = row.value(QStringLiteral("subvolume")).toString();
        const QString target = row.value(QStringLiteral("target")).toString();
        QString options = QStringLiteral("subvol=%1,%2")
                              .arg(subvol, row.value(QStringLiteral("options")).toString());
        if (subvol == QLatin1String(kRootSubvol)) {
            options.append(QLatin1Char(','));
            options.append(QLatin1String(kRootSpaceCache));
        }
        content.append(formatRow(btrfsUuid, target, QStringLiteral("btrfs"),
                                 options, 0, 0).toUtf8());
    }
    content.append(formatRow(espUuid, QStringLiteral("/boot/efi"),
                             QStringLiteral("vfat"), QLatin1String(kEspOptions),
                             0, 2).toUtf8());
    return content;
}

} // namespace

SlmFstabJob::SlmFstabJob(QObject *parent)
    : Calamares::CppJob(parent)
{
}

SlmFstabJob::~SlmFstabJob() = default;

QString SlmFstabJob::prettyName() const
{
    return tr("Generate /etc/fstab");
}

Calamares::JobResult SlmFstabJob::exec()
{
    auto *gs = Calamares::JobQueue::instanceGlobalStorage();
    if (!gs) {
        return Calamares::JobResult::error(
            tr("Installer state unavailable."),
            QStringLiteral("FSTAB_001: GlobalStorage missing"));
    }

    const QString rootDevice = gs->value(QStringLiteral("slm.target.root_device")).toString();
    const QString espDevice = gs->value(QStringLiteral("slm.target.esp_device")).toString();
    const QVariantList mountPlan = gs->value(QStringLiteral("slm.btrfs.mount_plan")).toList();
    if (rootDevice.isEmpty() || espDevice.isEmpty() || mountPlan.isEmpty()) {
        return Calamares::JobResult::error(
            tr("Filesystem layout not yet planned."),
            QStringLiteral("FSTAB_001: missing slm.target.root_device, "
                           "slm.target.esp_device, or slm.btrfs.mount_plan"));
    }

    QString btrfsUuid;
    QString espUuid;
    if (m_dryRun) {
        btrfsUuid = QStringLiteral("<btrfs-uuid>");
        espUuid = QStringLiteral("<esp-uuid>");
    } else {
        btrfsUuid = readUuid(rootDevice);
        espUuid = readUuid(espDevice);
        if (btrfsUuid.isEmpty() || espUuid.isEmpty()) {
            return Calamares::JobResult::error(
                tr("Unable to read partition UUIDs."),
                QStringLiteral("FSTAB_002: blkid failed for %1 or %2")
                    .arg(rootDevice, espDevice));
        }
    }

    const QByteArray content = buildFstab(btrfsUuid, espUuid, mountPlan);

    const QString rootMount = resolveRootMountPoint(gs);
    const QString fstabPath = rootMount + QStringLiteral("/etc/fstab");

    cDebug() << "slm-fstab:"
             << "btrfs_uuid=" << btrfsUuid
             << "esp_uuid=" << espUuid
             << "fstab_path=" << fstabPath
             << "dry_run=" << m_dryRun;

    if (m_dryRun) {
        cDebug() << "slm-fstab: DRY RUN — would write to" << fstabPath << ":\n"
                 << QString::fromUtf8(content);
        gs->insert(QStringLiteral("slm.fstab.dry_run"), true);
        gs->insert(QStringLiteral("slm.fstab.preview"), QString::fromUtf8(content));
        return Calamares::JobResult::ok();
    }

    // Defense in depth — see slm-partition for the rationale.
    if (!gs->value(QStringLiteral("slm.target.confirmed")).toBool()) {
        return Calamares::JobResult::error(
            tr("Installation has not been confirmed."),
            QStringLiteral("FSTAB_006: slm.target.confirmed not set"));
    }

    const QFileInfo info(fstabPath);
    if (!QDir().mkpath(info.absolutePath())) {
        return Calamares::JobResult::error(
            tr("Unable to prepare /etc directory in target."),
            QStringLiteral("FSTAB_003: mkpath failed for %1").arg(info.absolutePath()));
    }
    QFile out(fstabPath);
    if (!out.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        return Calamares::JobResult::error(
            tr("Unable to write /etc/fstab in target."),
            QStringLiteral("FSTAB_003: open(%1) failed: %2").arg(fstabPath, out.errorString()));
    }
    if (out.write(content) != content.size()) {
        const QString err = out.errorString();
        out.close();
        return Calamares::JobResult::error(
            tr("Unable to write /etc/fstab in target."),
            QStringLiteral("FSTAB_003: short write to %1: %2").arg(fstabPath, err));
    }
    out.close();
    gs->insert(QStringLiteral("slm.fstab.path"), fstabPath);
    return Calamares::JobResult::ok();
}

void SlmFstabJob::setConfigurationMap(const QVariantMap &configurationMap)
{
    if (configurationMap.contains(QStringLiteral("dry-run"))) {
        m_dryRun = configurationMap.value(QStringLiteral("dry-run")).toBool();
    }
}
