#!/usr/bin/env bash
set -euo pipefail

# Install/update recovery boot entry from generated templates.
# Requires root privileges.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_DIR="${SLM_RECOVERY_OUT_DIR:-$ROOT_DIR/build/recovery-partition}"
BOOTLOADER="${SLM_RECOVERY_BOOTLOADER:-auto}" # auto|systemd-boot|grub
ENTRY_ID="${SLM_RECOVERY_ENTRY_ID:-slm-recovery}"
KERNEL_PATH="${SLM_RECOVERY_KERNEL_PATH:-/vmlinuz-linux}"
INITRD_PATH="${SLM_RECOVERY_INITRD_PATH:-/initramfs-linux.img}"
ROOT_SPEC="${SLM_RECOVERY_ROOT_SPEC:-}"
ROOT_DEVICE="${SLM_RECOVERY_ROOT_DEVICE:-}"

log() { echo "[install-recovery-boot-entry] $*"; }
die() { echo "[install-recovery-boot-entry][FAIL] $*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --artifact-dir PATH   Directory containing generated templates
  --bootloader NAME     auto|systemd-boot|grub
  --entry-id ID         Entry id (default: $ENTRY_ID)
  --kernel PATH         Kernel path if template is missing
  --initrd PATH         Initrd path if template is missing
  --root-spec SPEC      Root spec (e.g. PARTUUID=xxxx or UUID=xxxx)
  --root-device DEV     Block device to auto-resolve root spec
  --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --artifact-dir) ARTIFACT_DIR="$2"; shift 2 ;;
    --bootloader) BOOTLOADER="$2"; shift 2 ;;
    --entry-id) ENTRY_ID="$2"; shift 2 ;;
    --kernel) KERNEL_PATH="$2"; shift 2 ;;
    --initrd) INITRD_PATH="$2"; shift 2 ;;
    --root-spec) ROOT_SPEC="$2"; shift 2 ;;
    --root-device) ROOT_DEVICE="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

if [[ "${EUID}" -ne 0 ]]; then
  die "run as root"
fi

detect_bootloader() {
  if [[ "$BOOTLOADER" != "auto" ]]; then
    echo "$BOOTLOADER"
    return 0
  fi
  if command -v bootctl >/dev/null 2>&1; then
    echo "systemd-boot"
    return 0
  fi
  if command -v update-grub >/dev/null 2>&1 || command -v grub-mkconfig >/dev/null 2>&1; then
    echo "grub"
    return 0
  fi
  die "cannot auto-detect bootloader"
}

resolve_root_spec() {
  if [[ -n "$ROOT_SPEC" ]]; then
    echo "$ROOT_SPEC"
    return 0
  fi

  if [[ -n "$ROOT_DEVICE" ]]; then
    [[ -b "$ROOT_DEVICE" ]] || die "root device is not a block device: $ROOT_DEVICE"
    local partuuid=""
    local uuid=""
    partuuid="$(blkid -s PARTUUID -o value "$ROOT_DEVICE" 2>/dev/null || true)"
    uuid="$(blkid -s UUID -o value "$ROOT_DEVICE" 2>/dev/null || true)"
    if [[ -n "$partuuid" ]]; then
      echo "PARTUUID=$partuuid"
      return 0
    fi
    if [[ -n "$uuid" ]]; then
      echo "UUID=$uuid"
      return 0
    fi
    die "cannot resolve PARTUUID/UUID from device: $ROOT_DEVICE"
  fi

  die "root spec is required (use --root-spec or --root-device)"
}

render_template() {
  local src="$1"
  local root_spec="$2"
  local kernel="$3"
  local initrd="$4"
  if [[ -f "$src" ]]; then
    sed \
      -e "s#@ROOT_SPEC@#$root_spec#g" \
      -e "s#@KERNEL_PATH@#$kernel#g" \
      -e "s#@INITRD_PATH@#$initrd#g" \
      "$src"
    return 0
  fi
  return 1
}

install_systemd_boot() {
  local resolved_root_spec="$1"
  local loader_dir=""
  for d in /boot/loader/entries /boot/efi/loader/entries /efi/loader/entries; do
    if [[ -d "$d" ]]; then
      loader_dir="$d"
      break
    fi
  done
  [[ -n "$loader_dir" ]] || die "loader entries directory not found"

  local src="$ARTIFACT_DIR/slm-recovery-systemd-boot.conf.template"
  local dst="$loader_dir/$ENTRY_ID.conf"
  if render_template "$src" "$resolved_root_spec" "$KERNEL_PATH" "$INITRD_PATH" > "$dst"; then
    :
  else
    cat > "$dst" <<EOF
title   SLM Recovery
linux   $KERNEL_PATH
initrd  $INITRD_PATH
options root=$resolved_root_spec rootfstype=squashfs ro quiet systemd.unit=multi-user.target slm.recovery=1
EOF
  fi
  log "installed systemd-boot entry: $dst"
}

install_grub() {
  local resolved_root_spec="$1"
  local dst="/etc/grub.d/42_slm_recovery"
  local src="$ARTIFACT_DIR/slm-recovery-grub.cfg.template"
  {
    echo "#!/bin/sh"
    echo "exec tail -n +3 \$0"
    echo "# Automatically generated by SLM recovery installer"
    if render_template "$src" "$resolved_root_spec" "$KERNEL_PATH" "$INITRD_PATH"; then
      :
    else
      cat <<EOF
menuentry 'SLM Recovery' {
    linux $KERNEL_PATH root=$resolved_root_spec rootfstype=squashfs ro quiet systemd.unit=multi-user.target slm.recovery=1
    initrd $INITRD_PATH
}
EOF
    fi
  } > "$dst"
  chmod 755 "$dst"
  log "installed GRUB snippet: $dst"

  if command -v update-grub >/dev/null 2>&1; then
    update-grub
    log "ran update-grub"
  elif command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o /boot/grub/grub.cfg
    log "ran grub-mkconfig"
  else
    log "skip grub config regeneration (tool not found)"
  fi
}

RESOLVED_ROOT_SPEC="$(resolve_root_spec)"
log "using root spec: $RESOLVED_ROOT_SPEC"

case "$(detect_bootloader)" in
  systemd-boot) install_systemd_boot "$RESOLVED_ROOT_SPEC" ;;
  grub) install_grub "$RESOLVED_ROOT_SPEC" ;;
  *) die "unsupported bootloader: $BOOTLOADER" ;;
esac

log "done"
