#!/usr/bin/env bash
set -euo pipefail

# Install/update recovery boot entry from generated templates.
# Requires root privileges.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ARTIFACT_DIR="${SLM_RECOVERY_OUT_DIR:-$ROOT_DIR/build/recovery-partition}"
BOOTLOADER="${SLM_RECOVERY_BOOTLOADER:-auto}" # auto|systemd-boot|grub
ENTRY_ID="${SLM_RECOVERY_ENTRY_ID:-slm-recovery}"
KERNEL_PATH="${SLM_RECOVERY_KERNEL_PATH:-/vmlinuz-linux}"
INITRD_PATH="${SLM_RECOVERY_INITRD_PATH:-/initramfs-linux.img}"

log() { echo "[install-recovery-boot-entry] $*"; }
die() { echo "[install-recovery-boot-entry][FAIL] $*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --artifact-dir PATH   Directory containing generated templates
  --bootloader NAME     auto|systemd-boot|grub
  --entry-id ID         Entry id (default: $ENTRY_ID)
  --kernel PATH         Kernel path if template is missing
  --initrd PATH         Initrd path if template is missing
  --help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --artifact-dir) ARTIFACT_DIR="$2"; shift 2 ;;
    --bootloader) BOOTLOADER="$2"; shift 2 ;;
    --entry-id) ENTRY_ID="$2"; shift 2 ;;
    --kernel) KERNEL_PATH="$2"; shift 2 ;;
    --initrd) INITRD_PATH="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

if [[ "${EUID}" -ne 0 ]]; then
  die "run as root"
fi

detect_bootloader() {
  if [[ "$BOOTLOADER" != "auto" ]]; then
    echo "$BOOTLOADER"
    return 0
  fi
  if command -v bootctl >/dev/null 2>&1; then
    echo "systemd-boot"
    return 0
  fi
  if command -v update-grub >/dev/null 2>&1 || command -v grub-mkconfig >/dev/null 2>&1; then
    echo "grub"
    return 0
  fi
  die "cannot auto-detect bootloader"
}

install_systemd_boot() {
  local loader_dir=""
  for d in /boot/loader/entries /boot/efi/loader/entries /efi/loader/entries; do
    if [[ -d "$d" ]]; then
      loader_dir="$d"
      break
    fi
  done
  [[ -n "$loader_dir" ]] || die "loader entries directory not found"

  local src="$ARTIFACT_DIR/slm-recovery-systemd-boot.conf.template"
  local dst="$loader_dir/$ENTRY_ID.conf"
  if [[ -f "$src" ]]; then
    install -Dm644 "$src" "$dst"
  else
    cat > "$dst" <<EOF
title   SLM Recovery
linux   $KERNEL_PATH
initrd  $INITRD_PATH
options root=LABEL=SLM_RECOVERY rootfstype=squashfs ro quiet systemd.unit=multi-user.target slm.recovery=1
EOF
  fi
  log "installed systemd-boot entry: $dst"
}

install_grub() {
  local dst="/etc/grub.d/42_slm_recovery"
  local src="$ARTIFACT_DIR/slm-recovery-grub.cfg.template"
  {
    echo "#!/bin/sh"
    echo "exec tail -n +3 \$0"
    echo "# Automatically generated by SLM recovery installer"
    if [[ -f "$src" ]]; then
      cat "$src"
    else
      cat <<EOF
menuentry 'SLM Recovery' {
    linux $KERNEL_PATH root=LABEL=SLM_RECOVERY rootfstype=squashfs ro quiet systemd.unit=multi-user.target slm.recovery=1
    initrd $INITRD_PATH
}
EOF
    fi
  } > "$dst"
  chmod 755 "$dst"
  log "installed GRUB snippet: $dst"

  if command -v update-grub >/dev/null 2>&1; then
    update-grub
    log "ran update-grub"
  elif command -v grub-mkconfig >/dev/null 2>&1; then
    grub-mkconfig -o /boot/grub/grub.cfg
    log "ran grub-mkconfig"
  else
    log "skip grub config regeneration (tool not found)"
  fi
}

case "$(detect_bootloader)" in
  systemd-boot) install_systemd_boot ;;
  grub) install_grub ;;
  *) die "unsupported bootloader: $BOOTLOADER" ;;
esac

log "done"
