#!/usr/bin/env bash
set -euo pipefail

# Non-destructive helper to prepare a history-preserving split repository
# for slm-settings using git-filter-repo.
#
# Usage:
#   scripts/prepare-settings-history-split.sh [output-dir]
#
# Example:
#   scripts/prepare-settings-history-split.sh /tmp/slm-settings-repo
#
# Optional:
#   ALLOW_SNAPSHOT_FALLBACK=0 scripts/prepare-settings-history-split.sh ...
#   (force history-preserving mode only; fail if git-filter-repo is unavailable)

OUTPUT_DIR="${1:-/tmp/slm-settings-repo}"
ALLOW_SNAPSHOT_FALLBACK="${ALLOW_SNAPSHOT_FALLBACK:-1}"
WORK_DIR="$(mktemp -d /tmp/slm-settings-split.XXXXXX)"
PATHS_FILE="modules/slm-settings/docs/EXTRACTION_PATHS.txt"
HAS_HISTORY_PATHS=1
FORCE_SNAPSHOT_FALLBACK=0

cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

commit_scaffolding_if_dirty() {
  local out_dir="$1"
  if ! git -C "$out_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    return 0
  fi
  if [[ -z "$(git -C "$out_dir" status --porcelain)" ]]; then
    return 0
  fi
  git -C "$out_dir" config user.name "SLM Build Bot" || true
  git -C "$out_dir" config user.email "slm-buildbot@local" || true
  git -C "$out_dir" add .
  git -C "$out_dir" commit -q -m "Add standalone split scaffolding (docs + CI placeholder)"
}

materialize_standalone_layout() {
  local out_dir="$1"

  mkdir -p "$out_dir/.github/workflows" "$out_dir/docs" "$out_dir/scripts"

  cat > "$out_dir/README.md" <<'DOC'
# slm-settings

Standalone split repository prepared from `slm-desktop` monorepo.

## Source scope
- `src/apps/settings/*`
- `Qml/apps/settings/*`
- selected runtime/service assets used by settings flow

## Suggested next steps
1. Push this repo to new remote.
2. Add CI and standalone build boundary incrementally.
3. Integrate back to monorepo via submodule or package pin.
DOC

  cat > "$out_dir/.github/workflows/ci.yml" <<'YAML'
name: settings-split-smoke

on:
  push:
  pull_request:

jobs:
  verify-layout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify core paths
        run: |
          test -d src/apps/settings
          test -d Qml/apps/settings
YAML

  cat > "$out_dir/scripts/ci-smoke.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

test -d src/apps/settings
test -d Qml/apps/settings
echo "[settings-split] smoke ok"
SH
  chmod +x "$out_dir/scripts/ci-smoke.sh"

  cat > "$out_dir/docs/MIGRATION.md" <<'DOC'
# Migration notes

This repository is generated by `scripts/prepare-settings-history-split.sh`.

- If generated with snapshot fallback, history is not preserved.
- For full history, install `git-filter-repo` and rerun with:

```bash
ALLOW_SNAPSHOT_FALLBACK=0 scripts/prepare-settings-history-split.sh /tmp/slm-settings-repo
```
DOC
}

if [[ ! -f "$PATHS_FILE" ]]; then
  echo "[settings-split] missing path manifest: $PATHS_FILE" >&2
  exit 1
fi

rm -rf "$OUTPUT_DIR"

while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  if ! git cat-file -e "HEAD:$path" >/dev/null 2>&1; then
    HAS_HISTORY_PATHS=0
    break
  fi
done < "$PATHS_FILE"

if ! command -v git-filter-repo >/dev/null 2>&1; then
  if [[ "$HAS_HISTORY_PATHS" != "1" ]]; then
    if [[ "$ALLOW_SNAPSHOT_FALLBACK" != "1" ]]; then
      echo "[settings-split] manifest paths are not present in HEAD history; cannot perform history-preserving split." >&2
      exit 1
    fi
    FORCE_SNAPSHOT_FALLBACK=1
  fi

  if [[ "$FORCE_SNAPSHOT_FALLBACK" != "1" ]] && git fast-export --help >/dev/null 2>&1; then
    echo "[settings-split] git-filter-repo not found; using git fast-export/import fallback (history preserved)."
    git clone --no-local . "$WORK_DIR/repo"
    pushd "$WORK_DIR/repo" >/dev/null
    CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    PATH_SPECS=()
    while IFS= read -r path; do
      [[ -z "$path" ]] && continue
      PATH_SPECS+=("$path")
    done < "$OLDPWD/$PATHS_FILE"
    mkdir -p "$OUTPUT_DIR"
    pushd "$OUTPUT_DIR" >/dev/null
    git init -q
    popd >/dev/null
    git fast-export --tag-of-filtered-object=drop --all -- "${PATH_SPECS[@]}" | (cd "$OUTPUT_DIR" && git fast-import --quiet)
    if git -C "$OUTPUT_DIR" show-ref --verify --quiet "refs/heads/${CURRENT_BRANCH}"; then
      git -C "$OUTPUT_DIR" checkout -q "${CURRENT_BRANCH}"
    elif git -C "$OUTPUT_DIR" show-ref --verify --quiet "refs/heads/main"; then
      git -C "$OUTPUT_DIR" checkout -q main
    elif git -C "$OUTPUT_DIR" show-ref --verify --quiet "refs/heads/master"; then
      git -C "$OUTPUT_DIR" checkout -q master
    fi
    git -C "$OUTPUT_DIR" gc --prune=now >/dev/null 2>&1 || true
    popd >/dev/null
    materialize_standalone_layout "$OUTPUT_DIR"
    commit_scaffolding_if_dirty "$OUTPUT_DIR"
    echo "[settings-split] history-preserving fallback repository prepared at: $OUTPUT_DIR"
    exit 0
  fi

  if [[ "$ALLOW_SNAPSHOT_FALLBACK" != "1" ]]; then
    echo "[settings-split] no history-preserving splitter available (git-filter-repo/fast-export)." >&2
    exit 1
  fi

  if [[ "$FORCE_SNAPSHOT_FALLBACK" == "1" ]]; then
    echo "[settings-split] manifest paths are not present in committed HEAD; creating snapshot fallback (no history)."
  else
    echo "[settings-split] no history-preserving splitter available; creating snapshot fallback (no history)."
  fi
  mkdir -p "$OUTPUT_DIR"
  while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    if [[ -e "$path" ]]; then
      mkdir -p "$OUTPUT_DIR/$(dirname "$path")"
      cp -a "$path" "$OUTPUT_DIR/$path"
    fi
  done < "$PATHS_FILE"

  pushd "$OUTPUT_DIR" >/dev/null
  git init -q
  git config user.name "SLM Build Bot"
  git config user.email "slm-buildbot@local"
  materialize_standalone_layout "$OUTPUT_DIR"
  git add .
  git commit -q -m "Initial slm-settings snapshot split (fallback, no history)"
  popd >/dev/null

  echo "[settings-split] snapshot repository prepared at: $OUTPUT_DIR"
  if [[ "$FORCE_SNAPSHOT_FALLBACK" == "1" ]]; then
    echo "[settings-split] commit settings paths first, then rerun for history-preserving split."
  else
    echo "[settings-split] install git-filter-repo and rerun for full history-preserving split."
  fi
  exit 0
fi

if [[ "$HAS_HISTORY_PATHS" != "1" || "$FORCE_SNAPSHOT_FALLBACK" == "1" ]]; then
  if [[ "$ALLOW_SNAPSHOT_FALLBACK" != "1" ]]; then
    echo "[settings-split] manifest paths are not present in HEAD history; cannot perform history-preserving split." >&2
    exit 1
  fi
  echo "[settings-split] manifest paths are not present in HEAD history; using snapshot fallback."
  mkdir -p "$OUTPUT_DIR"
  while IFS= read -r path; do
    [[ -z "$path" ]] && continue
    if [[ -e "$path" ]]; then
      mkdir -p "$OUTPUT_DIR/$(dirname "$path")"
      cp -a "$path" "$OUTPUT_DIR/$path"
    fi
  done < "$PATHS_FILE"

  pushd "$OUTPUT_DIR" >/dev/null
  git init -q
  git config user.name "SLM Build Bot"
  git config user.email "slm-buildbot@local"
  materialize_standalone_layout "$OUTPUT_DIR"
  git add .
  git commit -q -m "Initial slm-settings snapshot split (fallback, no history)"
  popd >/dev/null

  echo "[settings-split] snapshot repository prepared at: $OUTPUT_DIR"
  echo "[settings-split] after settings paths are committed, rerun for history-preserving split."
  exit 0
fi

echo "[settings-split] cloning current repo to temporary workspace..."
git clone --no-local . "$WORK_DIR/repo"

pushd "$WORK_DIR/repo" >/dev/null

FILTER_ARGS=()
while IFS= read -r path; do
  [[ -z "$path" ]] && continue
  FILTER_ARGS+=(--path "$path")
done < "$OLDPWD/$PATHS_FILE"

echo "[settings-split] filtering history by manifest paths..."
git filter-repo "${FILTER_ARGS[@]}" --force

mkdir -p "$OUTPUT_DIR"
cp -a . "$OUTPUT_DIR/"
popd >/dev/null

materialize_standalone_layout "$OUTPUT_DIR"
commit_scaffolding_if_dirty "$OUTPUT_DIR"

echo "[settings-split] split repository prepared at: $OUTPUT_DIR"
echo "[settings-split] next recommended step:"
echo "  cd $OUTPUT_DIR && git remote add origin <new-slm-settings-repo-url> && git push -u origin HEAD"
