# C++ sources grouped by responsibility.

set(DESKTOP_SHELL_APP_ENTRY
    main.cpp
)

set(DESKTOP_SHELL_MODELS_AND_RUNTIME
    appmodel.cpp
    appmodel.h
    src/bootstrap/appstartupargs.cpp
    src/bootstrap/appstartupargs.h
    src/bootstrap/appstartupbridge.cpp
    src/bootstrap/appstartupbridge.h
    src/bootstrap/daemonservicebootstrap.cpp
    src/bootstrap/daemonservicebootstrap.h
    src/bootstrap/daemonservicebootstraprunner.cpp
    src/bootstrap/daemonservicebootstraprunner.h
    src/core/execution/appcommandrouter.cpp
    src/core/execution/appcommandrouter.h
    dockidentity.cpp
    dockidentity.h
    dockmodel.cpp
    dockmodel.h
    dockidentity.cpp
    dockidentity.h
    shortcutmodel.cpp
    shortcutmodel.h
    src/core/execution/appruntimeregistry.cpp
    src/core/execution/appruntimeregistry.h
    src/core/execution/appexecutiongate.cpp
    src/core/execution/appexecutiongate.h
    src/core/execution/appruntimeregistry.cpp
    src/core/execution/appruntimeregistry.h
    src/core/launcher/applauncher.cpp
    src/core/launcher/applauncher.h
    src/core/launcher/launchenvresolver.cpp
    src/core/launcher/launchenvresolver.h
    src/core/workspace/spacesmanager.cpp
    src/core/workspace/spacesmanager.h
    src/core/workspace/workspacemanager.cpp
    src/core/workspace/workspacemanager.h
    src/core/workspace/workspacestripmodel.cpp
    src/core/workspace/workspacestripmodel.h
    src/core/workspace/multitaskingcontroller.cpp
    src/core/workspace/multitaskingcontroller.h
    src/core/workspace/windowthumbnaillayoutengine.cpp
    src/core/workspace/windowthumbnaillayoutengine.h
    src/core/motion/slmmotiontypes.cpp
    src/core/motion/slmmotiontypes.h
    src/core/motion/slmmotionpresetlibrary.cpp
    src/core/motion/slmmotionpresetlibrary.h
    src/core/motion/slmspringsolver.cpp
    src/core/motion/slmspringsolver.h
    src/core/motion/slmphysicsintegrator.cpp
    src/core/motion/slmphysicsintegrator.h
    src/core/motion/slmmotionvalue.cpp
    src/core/motion/slmmotionvalue.h
    src/core/motion/slmanimationengine.cpp
    src/core/motion/slmanimationengine.h
    src/core/motion/slmanimationscheduler.cpp
    src/core/motion/slmanimationscheduler.h
    src/core/motion/slmgesturebinding.cpp
    src/core/motion/slmgesturebinding.h
    src/core/motion/slmmotioncontroller.cpp
    src/core/motion/slmmotioncontroller.h
    src/core/shell/shellstatecontroller.cpp
    src/core/shell/shellstatecontroller.h
    src/core/shell/shellinputrouter.cpp
    src/core/shell/shellinputrouter.h
    src/core/shell/shelllayerwatchdog.cpp
    src/core/shell/shelllayerwatchdog.h
    src/daemon/desktopd/daemonhealthmonitor.cpp
    src/daemon/desktopd/daemonhealthmonitor.h
    src/daemon/desktopd/desktopdaemonservice.cpp
    src/daemon/desktopd/desktopdaemonservice.h
)

set(FILEMANAGER_APP_SOURCES
    src/apps/filemanager/filemanagerapi.cpp
    src/apps/filemanager/filemanagerapi_open.cpp
    src/apps/filemanager/filemanagerapi_archive.cpp
    src/apps/filemanager/filemanagerapi_favorites.cpp
    src/apps/filemanager/filemanagerapi_watch.cpp
    src/apps/filemanager/filemanagerapi_thumbnail.cpp
    src/apps/filemanager/filemanagerapi_batch.cpp
    src/apps/filemanager/filemanagerapi_recent.cpp
    src/apps/filemanager/filemanagerapi_openwith.cpp
    src/apps/filemanager/filemanagerapi_slmactions.cpp
    src/apps/filemanager/filemanagerapi_storage.cpp
    src/apps/filemanager/filemanagerapi_fs.cpp
    src/apps/filemanager/filemanagerapi_listing.cpp
    src/apps/filemanager/filemanagerapi_io.cpp
    src/apps/filemanager/filemanagerapi_metadata.cpp
    src/apps/filemanager/filemanagerapi_sharing.cpp
    src/apps/filemanager/filemanagerapi_portal.cpp
    src/apps/filemanager/filemanagerapi_daemon_transfer.cpp
    src/apps/filemanager/filemanagerapi_daemon_state.cpp
    src/apps/filemanager/filemanagerapi_daemon_remove.cpp
    src/apps/filemanager/filemanagerapi_daemon_emptytrash.cpp
    src/apps/filemanager/filemanagerapi_daemon_control.cpp
    src/apps/filemanager/filemanagerapi_daemon_recovery_state.cpp
    src/apps/filemanager/filemanagerapi_daemon_recovery_signals.cpp
    src/apps/filemanager/filemanagerapi_batch_control.cpp
    src/apps/filemanager/include/filemanagerapi.h
    src/apps/filemanager/filemanagermodel.cpp
    src/apps/filemanager/include/filemanagermodel.h
    src/apps/filemanager/filemanagermodelfactory.cpp
    src/apps/filemanager/include/filemanagermodelfactory.h
)

set(FILEMANAGER_OPS_SERVICE_SOURCES
    src/apps/filemanager/ops/fileoperationsmanager.cpp
    src/apps/filemanager/ops/fileoperationsmanager.h
    src/apps/filemanager/ops/fileoperationserrors.h
    src/apps/filemanager/ops/fileoperationsservice.cpp
    src/apps/filemanager/ops/fileoperationsservice.h
)

set(FILEMANAGER_PROGRESS_SOURCES
    src/apps/filemanager/ops/globalprogresscenter.cpp
    src/apps/filemanager/ops/globalprogresscenter.h
)

set(SLM_ACTION_FRAMEWORK_SOURCES
    src/core/actions/slmactiontypes.cpp
    src/core/actions/slmactiontypes.h
    src/core/actions/slmactioncondition.cpp
    src/core/actions/slmactioncondition.h
    src/core/actions/slmdesktopactionparser.cpp
    src/core/actions/slmdesktopactionparser.h
    src/core/actions/slmactiondiscovery.cpp
    src/core/actions/slmactiondiscovery.h
    src/core/actions/slmactionregistry.cpp
    src/core/actions/slmactionregistry.h
    src/core/actions/framework/slmdesktopentryscanner.cpp
    src/core/actions/framework/slmdesktopentryscanner.h
    src/core/actions/framework/slmframeworktypes.h
    src/core/actions/framework/acl/slmacllexer.cpp
    src/core/actions/framework/acl/slmacllexer.h
    src/core/actions/framework/acl/slmaclparser.cpp
    src/core/actions/framework/acl/slmaclparser.h
    src/core/actions/framework/slmdesktopentryparsermodule.cpp
    src/core/actions/framework/slmdesktopentryparsermodule.h
    src/core/actions/framework/slmmetadataparser.cpp
    src/core/actions/framework/slmmetadataparser.h
    src/core/actions/framework/slmactionregistryindex.cpp
    src/core/actions/framework/slmactionregistryindex.h
    src/core/actions/framework/slmactioncachelayer.cpp
    src/core/actions/framework/slmactioncachelayer.h
    src/core/actions/framework/slmcachemanager.cpp
    src/core/actions/framework/slmcachemanager.h
    src/core/actions/framework/slmcapabilityresolverlayer.cpp
    src/core/actions/framework/slmcapabilityresolverlayer.h
    src/core/actions/framework/slmcapabilitybuilders.cpp
    src/core/actions/framework/slmcapabilitybuilders.h
    src/core/actions/framework/slmgrouptreebuilder.cpp
    src/core/actions/framework/slmgrouptreebuilder.h
    src/core/actions/framework/slmactioninvoker.cpp
    src/core/actions/framework/slmactioninvoker.h
    src/core/actions/framework/slmactionframework.cpp
    src/core/actions/framework/slmactionframework.h
)

set(DESKTOP_SHELL_SERVICES
    src/services/network/networkmanager.cpp
    src/services/network/networkmanager.h
    src/apps/settings/desktopsettingsclient.cpp
    src/apps/settings/desktopsettingsclient.h
    src/services/power/batterymanager.cpp
    src/services/power/batterymanager.h
    src/services/power/powerbridge.cpp
    src/services/power/powerbridge.h
    src/services/bluetooth/bluetoothmanager.cpp
    src/services/bluetooth/bluetoothmanager.h
    src/services/notifications/notificationmanager.cpp
    src/services/notifications/notificationmanager.h
    src/services/notifications/desktopnotificationadaptor.cpp
    src/services/notifications/desktopnotificationadaptor.h
    src/services/sound/soundmanager.cpp
    src/services/sound/soundmanager.h
    src/services/media/mediasessionmanager.cpp
    src/services/media/mediasessionmanager.h
    src/services/indicator/statusnotifierhost.cpp
    src/services/indicator/statusnotifierhost.h
    src/services/portal/screencastprivacymodel.cpp
    src/services/portal/screencastprivacymodel.h
    src/services/portal/inputcaptureprivacymodel.cpp
    src/services/portal/inputcaptureprivacymodel.h
    cursorcontroller.cpp
    cursorcontroller.h
    src/core/icons/themeiconprovider.cpp
    src/core/icons/themeiconprovider.h
    src/core/icons/themeiconcontroller.cpp
    src/core/icons/themeiconcontroller.h
    externalindicatorregistry.cpp
    externalindicatorregistry.h
    globalmenumanager.cpp
    globalmenumanager.h
    src/core/workspace/kwinwaylandipcclient.cpp
    src/core/workspace/kwinwaylandipcclient.h
    src/core/workspace/kwinwaylandstatemodel.cpp
    src/core/workspace/kwinwaylandstatemodel.h
    src/core/workspace/kwinsupportinfoparser.cpp
    src/core/workspace/kwinsupportinfoparser.h
    src/core/workspace/windowingbackendmanager.cpp
    src/core/workspace/windowingbackendmanager.h
    src/core/workspace/compositorinputcapturebackendservice.cpp
    src/core/workspace/compositorinputcapturebackendservice.h
    src/core/workspace/compositorinputcaptureprimitiveservice.cpp
    src/core/workspace/compositorinputcaptureprimitiveservice.h
    src/core/workspace/workspacepreviewmanager.cpp
    src/core/workspace/workspacepreviewmanager.h
    src/core/workspace/overviewpreviewmanager.h
    src/core/system/componentregistry.cpp
    src/core/system/componentregistry.h
    src/core/system/dependencyguard.cpp
    src/core/system/dependencyguard.h
    src/core/system/missingcomponentcontroller.cpp
    src/core/system/missingcomponentcontroller.h
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
    screenshotmanager.cpp
    screenshotmanager.h
    portalchooserlogichelper.cpp
    portalchooserlogichelper.h
    screenshotsavehelper.cpp
    screenshotsavehelper.h
    portaluibridge.cpp
    portaluibridge.h
    metadataindexserver.cpp
    metadataindexserver.h
    tothespotservice.cpp
    tothespotservice.h
    tothespotcontextmenuhelper.cpp
    tothespotcontextmenuhelper.h
    tothespottexthighlighter.cpp
    tothespottexthighlighter.h
    ${FILEMANAGER_APP_SOURCES}
    ${FILEMANAGER_PROGRESS_SOURCES}
    src/filemanager/FileManagerShellBridge.cpp
    src/filemanager/FileManagerShellBridge.h
    src/filemanager/ThumbnailImageProvider.cpp
    src/filemanager/ThumbnailImageProvider.h
    ${SLM_ACTION_FRAMEWORK_SOURCES}
    src/services/clipboard/clipboardtypes.h
    src/services/clipboard/contentclassifier.cpp
    src/services/clipboard/contentclassifier.h
    src/services/clipboard/StorageManager.cpp
    src/services/clipboard/StorageManager.h
    src/services/clipboard/ClipboardHistory.cpp
    src/services/clipboard/ClipboardHistory.h
    src/services/clipboard/ClipboardWatcher.cpp
    src/services/clipboard/ClipboardWatcher.h
    src/services/clipboard/ClipboardService.cpp
    src/services/clipboard/ClipboardService.h
    src/services/clipboard/DBusInterface.cpp
    src/services/clipboard/DBusInterface.h
    src/services/clipboard/ClipboardServiceClient.cpp
    src/services/clipboard/ClipboardServiceClient.h
    src/services/session/SessionStateClient.cpp
    src/services/session/SessionStateClient.h
    src/services/clipboard/ClipboardSearchProvider.cpp
    src/services/clipboard/ClipboardSearchProvider.h
    src/printing/core/PrintTypes.h
    src/printing/core/PrintSettingsModel.cpp
    src/printing/core/PrintSettingsModel.h
    src/printing/core/PrintTicketSerializer.cpp
    src/printing/core/PrintTicketSerializer.h
    src/printing/core/PrintSession.cpp
    src/printing/core/PrintSession.h
    src/printing/core/PrintPreviewModel.cpp
    src/printing/core/PrintPreviewModel.h
    src/printing/core/PrintJobBuilder.cpp
    src/printing/core/PrintJobBuilder.h
    src/printing/core/JobSubmitter.cpp
    src/printing/core/JobSubmitter.h
    src/printing/core/PrinterCapabilityProvider.cpp
    src/printing/core/PrinterCapabilityProvider.h
    src/printing/core/PrinterManager.cpp
    src/printing/core/PrinterManager.h
    src/printing/preview/IPdfRenderer.h
    src/printing/preview/FallbackPdfRenderer.h
    src/printing/preview/FallbackPdfRenderer.cpp
    src/printing/preview/PopplerPdfRenderer.h
    src/printing/preview/PopplerPdfRenderer.cpp
    src/printing/preview/PrintPreviewCache.h
    src/printing/preview/PrintPreviewCache.cpp
    src/printing/qml/PrintDialogController.h
    src/printing/qml/PrintDialogController.cpp
    src/printing/plugin/PluginFieldDescriptor.h
    src/printing/plugin/PluginDescriptorValidator.h
    src/printing/plugin/PluginDescriptorValidator.cpp
    src/printing/plugin/PluginFeatureResolver.h
    src/printing/plugin/PluginFeatureResolver.cpp
    src/printing/persistence/PrinterSettingsStore.h
    src/printing/persistence/PrinterSettingsStore.cpp
    src/printing/core/IBackendAdapter.h
    src/printing/core/PrintQueueModel.h
    src/printing/core/PrintQueueModel.cpp
    src/printing/core/CupsStatusWatcher.h
    src/printing/core/CupsStatusWatcher.cpp
    src/printing/core/PrinterAdminService.h
    src/printing/core/PrinterAdminService.cpp
    src/printing/adapter/CupsErrorTranslator.h
    src/printing/adapter/CupsErrorTranslator.cpp
    src/printing/adapter/CupsAdapter.h
    src/printing/adapter/CupsAdapter.cpp
    src/services/clipboard/WaylandClipboardWatcher.cpp
    src/services/clipboard/WaylandClipboardWatcher.h
    ${CMAKE_BINARY_DIR}/wayland-protocol.c
    ${CMAKE_BINARY_DIR}/wayland-client-protocol.h
    ${CMAKE_BINARY_DIR}/ext-data-control-v1-protocol.c
    ${CMAKE_BINARY_DIR}/ext-data-control-v1-client-protocol.h
)

set(WINDOWINGCTL_SOURCES
    src/cli/windowingctl.cpp
    src/core/workspace/windowingbackendmanager.cpp
    src/core/workspace/windowingbackendmanager.h
    src/core/workspace/kwinwaylandipcclient.cpp
    src/core/workspace/kwinwaylandipcclient.h
    src/core/workspace/kwinwaylandstatemodel.cpp
    src/core/workspace/kwinwaylandstatemodel.h
    src/core/workspace/kwinsupportinfoparser.cpp
    src/core/workspace/kwinsupportinfoparser.h
)

set(DESKTOPD_SOURCES
    src/daemon/desktopd/desktopd_main.cpp
    appmodel.cpp
    appmodel.h
    dockidentity.cpp
    dockidentity.h
    dockmodel.cpp
    dockmodel.h
    shortcutmodel.cpp
    shortcutmodel.h
    globalsearchservice.cpp
    globalsearchservice.h
    src/core/execution/appexecutiongate.cpp
    src/core/execution/appexecutiongate.h
    src/core/execution/appruntimeregistry.cpp
    src/core/execution/appruntimeregistry.h
    src/core/launcher/applauncher.cpp
    src/core/launcher/applauncher.h
    src/core/launcher/launchenvresolver.cpp
    src/core/launcher/launchenvresolver.h
    src/apps/settings/modules/developer/envserviceclient.cpp
    src/apps/settings/modules/developer/envserviceclient.h
    ${SLM_ACTION_FRAMEWORK_SOURCES}
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
    src/daemon/desktopd/daemonhealthmonitor.cpp
    src/daemon/desktopd/daemonhealthmonitor.h
    src/daemon/desktopd/desktopdaemonservice.cpp
    src/daemon/desktopd/desktopdaemonservice.h
    src/daemon/desktopd/slmcapabilityservice.cpp
    src/daemon/desktopd/slmcapabilityservice.h
    src/daemon/desktopd/slmcapabilityframeworkservice.cpp
    src/daemon/desktopd/slmcapabilityframeworkservice.h
    ${FILEMANAGER_OPS_SERVICE_SOURCES}
    src/daemon/desktopd/sessionstatemanager.cpp
    src/daemon/desktopd/sessionstatemanager.h
    src/daemon/desktopd/sessionauthenticator.cpp
    src/daemon/desktopd/sessionauthenticator.h
    src/daemon/desktopd/sessionunlockthrottle.cpp
    src/daemon/desktopd/sessionunlockthrottle.h
    src/daemon/desktopd/sessionstateservice.cpp
    src/daemon/desktopd/sessionstateservice.h
    src/daemon/desktopd/sessionstatecompatservice.cpp
    src/daemon/desktopd/sessionstatecompatservice.h
    src/daemon/desktopd/globalmenuservice.cpp
    src/daemon/desktopd/globalmenuservice.h
    src/daemon/desktopd/captureservice.cpp
    src/daemon/desktopd/captureservice.h
    src/daemon/desktopd/screencastservice.cpp
    src/daemon/desktopd/screencastservice.h
    src/daemon/desktopd/inputcapturebackend.cpp
    src/daemon/desktopd/inputcapturebackend.h
    src/daemon/desktopd/inputcaptureservice.cpp
    src/daemon/desktopd/inputcaptureservice.h
    src/daemon/desktopd/screencaststreambackend.cpp
    src/daemon/desktopd/screencaststreambackend.h
    src/daemon/desktopd/capturestreamingestor.cpp
    src/daemon/desktopd/capturestreamingestor.h
    src/daemon/desktopd/foldersharingservice.cpp
    src/daemon/desktopd/foldersharingservice.h
    src/core/workspace/workspacecompatservice.cpp
    src/core/workspace/workspacecompatservice.h
    src/core/workspace/workspacemanager.cpp
    src/core/workspace/workspacemanager.h
    src/core/workspace/spacesmanager.cpp
    src/core/workspace/spacesmanager.h
    src/core/workspace/windowingbackendmanager.cpp
    src/core/workspace/windowingbackendmanager.h
    src/core/workspace/kwinwaylandipcclient.cpp
    src/core/workspace/kwinwaylandipcclient.h
    src/core/workspace/kwinwaylandstatemodel.cpp
    src/core/workspace/kwinwaylandstatemodel.h
    src/core/workspace/kwinsupportinfoparser.cpp
    src/core/workspace/kwinsupportinfoparser.h
    src/services/clipboard/clipboardtypes.h
    src/services/clipboard/contentclassifier.cpp
    src/services/clipboard/contentclassifier.h
    src/services/clipboard/ClipboardSearchProvider.cpp
    src/services/clipboard/ClipboardSearchProvider.h
    src/printing/core/PrintTypes.h
    src/printing/core/PrintSettingsModel.cpp
    src/printing/core/PrintSettingsModel.h
    src/printing/core/PrintTicketSerializer.cpp
    src/printing/core/PrintTicketSerializer.h
    src/printing/core/PrintSession.cpp
    src/printing/core/PrintSession.h
    src/printing/core/PrintPreviewModel.cpp
    src/printing/core/PrintPreviewModel.h
    src/printing/preview/IPdfRenderer.h
    src/printing/preview/FallbackPdfRenderer.h
    src/printing/preview/FallbackPdfRenderer.cpp
    src/printing/preview/PrintPreviewCache.h
    src/printing/preview/PrintPreviewCache.cpp
    src/printing/core/PrintJobBuilder.cpp
    src/printing/core/PrintJobBuilder.h
    src/printing/core/JobSubmitter.cpp
    src/printing/core/JobSubmitter.h
    src/printing/core/PrinterCapabilityProvider.cpp
    src/printing/core/PrinterCapabilityProvider.h
    src/printing/core/PrinterManager.cpp
    src/printing/core/PrinterManager.h
)

set(SLM_FILEOPSD_SOURCES
    src/daemon/fileopsd/fileopsd_main.cpp
    ${FILEMANAGER_OPS_SERVICE_SOURCES}
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
)

set(SLM_DEVICESD_SOURCES
    src/daemon/devicesd/devicesd_main.cpp
    src/daemon/devicesd/devicesmanager.cpp
    src/daemon/devicesd/devicesmanager.h
    src/daemon/devicesd/devicesservice.cpp
    src/daemon/devicesd/devicesservice.h
    src/services/storage/storagemanager.cpp
    src/services/storage/storagemanager.h
    src/services/storage/storageattachnotifier.cpp
    src/services/storage/storageattachnotifier.h
    src/services/storage/storagepolicystore.cpp
    src/services/storage/storagepolicystore.h
    src/daemon/devicesd/devicescompatservice.cpp
    src/daemon/devicesd/devicescompatservice.h
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
)

set(SLM_PORTALD_SOURCES
    src/daemon/portald/portald_main.cpp
    src/daemon/portald/portalmanager.cpp
    src/daemon/portald/portalmanager.h
    src/daemon/portald/implportalservice.cpp
    src/daemon/portald/implportalservice.h
    src/daemon/portald/implportaladaptors.cpp
    src/daemon/portald/implportaladaptors.h
    src/daemon/portald/portalservice.cpp
    src/daemon/portald/portalservice.h
    src/daemon/portald/portal-adapter/PortalRequestObject.cpp
    src/daemon/portald/portal-adapter/PortalRequestObject.h
    src/daemon/portald/portal-adapter/PortalRequestManager.cpp
    src/daemon/portald/portal-adapter/PortalRequestManager.h
    src/daemon/portald/portal-adapter/PortalSessionObject.cpp
    src/daemon/portald/portal-adapter/PortalSessionObject.h
    src/daemon/portald/portal-adapter/PortalSessionManager.cpp
    src/daemon/portald/portal-adapter/PortalSessionManager.h
    src/daemon/portald/portal-adapter/PortalPermissionStoreAdapter.cpp
    src/daemon/portald/portal-adapter/PortalPermissionStoreAdapter.h
    src/daemon/portald/portal-adapter/PortalCapabilityMapper.cpp
    src/daemon/portald/portal-adapter/PortalCapabilityMapper.h
    src/daemon/portald/portal-adapter/PortalDialogBridge.cpp
    src/daemon/portald/portal-adapter/PortalDialogBridge.h
    src/daemon/portald/portal-adapter/PortalAccessMediator.cpp
    src/daemon/portald/portal-adapter/PortalAccessMediator.h
    src/daemon/portald/portal-adapter/PortalResponseSerializer.cpp
    src/daemon/portald/portal-adapter/PortalResponseSerializer.h
    src/daemon/portald/portal-adapter/PortalAppContextResolver.cpp
    src/daemon/portald/portal-adapter/PortalAppContextResolver.h
    src/daemon/portald/portal-adapter/PortalBackendService.cpp
    src/daemon/portald/portal-adapter/PortalBackendService.h
    src/daemon/portald/portal-adapter/PortalSecretBridge.cpp
    src/daemon/portald/portal-adapter/PortalSecretBridge.h
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
)

set(SLM_CLIPBOARDD_SOURCES
    src/daemon/clipboardd/clipboardd_main.cpp
    src/services/clipboard/clipboardtypes.h
    src/services/clipboard/contentclassifier.cpp
    src/services/clipboard/contentclassifier.h
    src/services/clipboard/StorageManager.cpp
    src/services/clipboard/StorageManager.h
    src/services/clipboard/ClipboardHistory.cpp
    src/services/clipboard/ClipboardHistory.h
    src/services/clipboard/ClipboardWatcher.cpp
    src/services/clipboard/ClipboardWatcher.h
    src/services/clipboard/ClipboardService.cpp
    src/services/clipboard/ClipboardService.h
    src/services/clipboard/DBusInterface.cpp
    src/services/clipboard/DBusInterface.h
    src/services/clipboard/WaylandClipboardWatcher.cpp
    src/services/clipboard/WaylandClipboardWatcher.h
    ${CMAKE_BINARY_DIR}/wayland-protocol.c
    ${CMAKE_BINARY_DIR}/wayland-client-protocol.h
    ${CMAKE_BINARY_DIR}/ext-data-control-v1-protocol.c
    ${CMAKE_BINARY_DIR}/ext-data-control-v1-client-protocol.h
    src/core/permissions/Capability.cpp
    src/core/permissions/Capability.h
    src/core/permissions/CallerIdentity.cpp
    src/core/permissions/CallerIdentity.h
    src/core/permissions/AccessContext.cpp
    src/core/permissions/AccessContext.h
    src/core/permissions/PolicyDecision.cpp
    src/core/permissions/PolicyDecision.h
    src/core/permissions/PermissionStore.cpp
    src/core/permissions/PermissionStore.h
    src/core/permissions/AuditLogger.cpp
    src/core/permissions/AuditLogger.h
    src/core/permissions/TrustResolver.cpp
    src/core/permissions/TrustResolver.h
    src/core/permissions/SensitiveContentPolicy.cpp
    src/core/permissions/SensitiveContentPolicy.h
    src/core/permissions/PolicyEngine.cpp
    src/core/permissions/PolicyEngine.h
    src/core/permissions/PermissionBroker.cpp
    src/core/permissions/PermissionBroker.h
    src/core/permissions/DBusSecurityGuard.cpp
    src/core/permissions/DBusSecurityGuard.h
)

# ── Login / Session Stack ─────────────────────────────────────────────────────

set(SLM_LOGIN_LIB_SOURCES
    src/login/libslmlogin/slmlogindefs.h
    src/login/libslmlogin/slmsessionstate.h
    src/login/libslmlogin/slmsessionstate.cpp
    src/login/libslmlogin/slmconfigmanager.h
    src/login/libslmlogin/slmconfigmanager.cpp
    src/login/libslmlogin/slmplatformcheck.h
    src/login/libslmlogin/slmplatformcheck.cpp
)

set(SLM_SESSION_BROKER_SOURCES
    src/login/session-broker/main.cpp
    src/login/session-broker/sessionbroker.h
    src/login/session-broker/sessionbroker.cpp
)

set(SLM_WATCHDOG_SOURCES
    src/login/watchdog/main.cpp
    src/login/watchdog/sessionwatchdog.h
    src/login/watchdog/sessionwatchdog.cpp
)

set(SLM_GREETER_SOURCES
    src/login/greeter/main.cpp
    src/login/greeter/greetdclient.h
    src/login/greeter/greetdclient.cpp
    src/login/greeter/greeterapp.h
    src/login/greeter/greeterapp.cpp
    src/core/system/componentregistry.cpp
    src/core/system/componentregistry.h
    src/core/system/dependencyguard.cpp
    src/core/system/dependencyguard.h
    src/core/system/missingcomponentcontroller.cpp
    src/core/system/missingcomponentcontroller.h
)

set(SLM_RECOVERY_APP_SOURCES
    src/login/recovery-app/main.cpp
    src/login/recovery-app/recoveryapp.h
    src/login/recovery-app/recoveryapp.cpp
    src/core/system/componentregistry.cpp
    src/core/system/componentregistry.h
    src/core/system/dependencyguard.cpp
    src/core/system/dependencyguard.h
    src/core/system/missingcomponentcontroller.cpp
    src/core/system/missingcomponentcontroller.h
)

set(SLM_POLKIT_AGENT_SOURCES
    src/login/polkit-agent/main.cpp
    src/login/polkit-agent/polkitagentapp.h
    src/login/polkit-agent/polkitagentapp.cpp
)

# ── Settings / Context Daemons ───────────────────────────────────────────────

set(SLM_SETTINGSD_SOURCES
    src/daemon/settingsd/settingsd_main.cpp
    src/services/settingsd/settingsservice.cpp
    src/services/settingsd/settingsservice.h
    src/services/settingsd/settingsstore.cpp
    src/services/settingsd/settingsstore.h
    src/services/theme-policy/appthemeclassifier.cpp
    src/services/theme-policy/appthemeclassifier.h
    src/services/theme-policy/themepolicyengine.cpp
    src/services/theme-policy/themepolicyengine.h
)

set(SLM_CONTEXTD_SOURCES
    src/daemon/contextd/contextd_main.cpp
    src/services/context/contextservice.cpp
    src/services/context/contextservice.h
    src/services/context/ruleengine.cpp
    src/services/context/ruleengine.h
)

set(SLM_FIREWALLD_SOURCES
    src/daemon/firewalld/firewalld_main.cpp
    src/daemon/firewalld/firewallservice.cpp
    src/daemon/firewalld/firewallservice.h
    src/daemon/firewalld/firewalldbusadaptor.cpp
    src/daemon/firewalld/firewalldbusadaptor.h
    src/daemon/firewalld/firewalltypes.h
    src/services/firewall/policyengine.cpp
    src/services/firewall/policyengine.h
    src/services/firewall/policystore.cpp
    src/services/firewall/policystore.h
    src/services/firewall/nftablesadapter.cpp
    src/services/firewall/nftablesadapter.h
    src/services/firewall/appidentityclient.cpp
    src/services/firewall/appidentityclient.h
)
